export const ActionTypes = {
  // Set types
  SET_USERS: "SET_USERS",
  SET_USER: "SET_USER",
  SET_THEME: "SET_THEME",
  SET_SELECTED_PAGE: "SET_SELECTED_PAGE",
  SET_FEEDBACKS: "SET_FEEDBACKS",
  SET_FEEDBACK: "SET_FEEDBACK",
  SET_RATES: "SET_RATES",
  SET_TOTAL_PROJECTS: "SET_TOTAL_PROJECTS",
  SET_TOTAL_EXPERIENCE: "SET_TOTAL_EXPERIENCE",
  SET_TOTAL_REVIEWS: "SET_TOTAL_REVIEWS",
  SET_CLIENT_LOCAL_PERCENT: "SET_CLIENT_LOCAL_PERCENT",
  SET_CLIENT_WORLDWIDE_PERCENT: "SET_CLIENT_WORLDWIDE_PERCENT",

  // Update types
  UPDATE_USERS: "UPDATE_USERS",
  UPDATE_USER: "UPDATE_USER",
  UPDATE_FEEDBACK: "UPDATE_FEEDBACK",

  // Delete types
  DELETE_USER: "DELETE_USER",

  // Remove types
  REMOVE_USER: "REMOVE_USER",

  //Logout User
  LOGOUT_USER: "LOGOUT_USER",
};
